### ISSUE TITLE
회원가입 (단체, 개인)

### ISSUE THREAD

**Issue by logpacket** [Blockchain-and-Beach/Clean-Funding#11]
개인 =>{
회원가입시 계정하나 생성,
Address => DB 저장
privateKey => Client에게 반환(공인인증서 개념)
}

단체 =>{
회원가입시 계정, namespace생성
addresss => DB저장 
privavteKey => 단체에게 반환(공인인증서 개념)
}

**Comment by jodnddus** [comment]
개인: 후원자
단체: 사회활동 주체
